"""initial schema

Revision ID: 338345ca03da
Revises:
Create Date: 2026-09-22 12:47:55.263793
"""

from collections.abc import Sequence

import sqlalchemy as sa

import app.db  # custom column types (Money, UTCDateTime)
from alembic import op

revision: str = "338345ca03da"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "admin_users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("full_name", sa.String(length=255), nullable=True),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("last_login_at", app.db.UTCDateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            app.db.UTCDateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            app.db.UTCDateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("admin_users", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_admin_users_email"), ["email"], unique=True)

    op.create_table(
        "banners",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=True),
        sa.Column("image_url", sa.String(length=500), nullable=True),
        sa.Column("cta_label", sa.String(length=120), nullable=True),
        sa.Column("cta_url", sa.String(length=500), nullable=True),
        sa.Column("starts_at", app.db.UTCDateTime(timezone=True), nullable=True),
        sa.Column("ends_at", app.db.UTCDateTime(timezone=True), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            app.db.UTCDateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            app.db.UTCDateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("banners", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_banners_active"), ["active"], unique=False)

    op.create_table(
        "brands",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("slug", sa.String(length=160), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("logo_url", sa.String(length=500), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            app.db.UTCDateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            app.db.UTCDateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    with op.batch_alter_table("brands", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_brands_active"), ["active"], unique=False)
        batch_op.create_index(batch_op.f("ix_brands_slug"), ["slug"], unique=True)

    op.create_table(
        "categories",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("slug", sa.String(length=160), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("image_url", sa.String(length=500), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            app.db.UTCDateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            app.db.UTCDateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    with op.batch_alter_table("categories", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_categories_active"), ["active"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_categories_slug"), ["slug"], unique=True)

    op.create_table(
        "customers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("full_name", sa.String(length=255), nullable=True),
        sa.Column("phone", sa.String(length=40), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("last_order_at", app.db.UTCDateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            app.db.UTCDateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            app.db.UTCDateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("customers", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_customers_email"), ["email"], unique=True)

    op.create_table(
        "homepage_sections",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "section_type",
            sa.Enum(
                "HERO",
                "FEATURED_PRODUCTS",
                "NEW_ARRIVALS",
                "CATEGORIES",
                "BRAND_STORY",
                "FEATURED_PRODUCT",
                "EDITORIAL",
                "OFFERS",
                "JOURNAL",
                "SOCIAL",
                "NEWSLETTER",
                name="homepagesectiontype",
                native_enum=False,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column("title", sa.String(length=255), nullable=True),
        sa.Column("subtitle", sa.String(length=255), nullable=True),
        sa.Column("body", sa.Text(), nullable=True),
        sa.Column("image_url", sa.String(length=500), nullable=True),
        sa.Column("cta_label", sa.String(length=120), nullable=True),
        sa.Column("cta_url", sa.String(length=500), nullable=True),
        sa.Column("visible", sa.Boolean(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            app.db.UTCDateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            app.db.UTCDateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("section_type"),
    )
    op.create_table(
        "posts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("slug", sa.String(length=255), nullable=False),
        sa.Column("excerpt", sa.String(length=500), nullable=True),
        sa.Column("content", sa.Text(), nullable=True),
        sa.Column("cover_image_url", sa.String(length=500), nullable=True),
        sa.Column("category", sa.String(length=120), nullable=True),
        sa.Column("author_name", sa.String(length=160), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "DRAFT",
                "PUBLISHED",
                "ARCHIVED",
                name="poststatus",
                native_enum=False,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column("featured", sa.Boolean(), nullable=False),
        sa.Column("published_at", app.db.UTCDateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            app.db.UTCDateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            app.db.UTCDateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("posts", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_posts_category"), ["category"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_posts_published_at"), ["published_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_posts_slug"), ["slug"], unique=True)
        batch_op.create_index(batch_op.f("ix_posts_status"), ["status"], unique=False)

    op.create_table(
        "promotions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("code", sa.String(length=64), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "discount_type",
            sa.Enum(
                "PERCENTAGE",
                "FIXED_AMOUNT",
                name="discounttype",
                native_enum=False,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column("discount_value", app.db.Money(precision=12, scale=2), nullable=False),
        sa.Column("starts_at", app.db.UTCDateTime(timezone=True), nullable=True),
        sa.Column("ends_at", app.db.UTCDateTime(timezone=True), nullable=True),
        sa.Column(
            "minimum_order_value", app.db.Money(precision=12, scale=2), nullable=True
        ),
        sa.Column("usage_limit", sa.Integer(), nullable=True),
        sa.Column("usage_count", sa.Integer(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            app.db.UTCDateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            app.db.UTCDateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint("discount_value > 0", name="ck_promotions_discount_positive"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("promotions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_promotions_active"), ["active"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_promotions_code"), ["code"], unique=True)
        batch_op.create_index(
            batch_op.f("ix_promotions_ends_at"), ["ends_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_promotions_starts_at"), ["starts_at"], unique=False
        )

    op.create_table(
        "site_settings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("brand_name", sa.String(length=160), nullable=False),
        sa.Column("owner_name", sa.String(length=160), nullable=True),
        sa.Column("tagline", sa.String(length=255), nullable=True),
        sa.Column("logo_url", sa.String(length=500), nullable=True),
        sa.Column("favicon_url", sa.String(length=500), nullable=True),
        sa.Column("contact_email", sa.String(length=255), nullable=True),
        sa.Column("contact_phone", sa.String(length=40), nullable=True),
        sa.Column("address", sa.String(length=500), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("shipping_information", sa.Text(), nullable=True),
        sa.Column("return_policy", sa.Text(), nullable=True),
        sa.Column("warranty_information", sa.Text(), nullable=True),
        sa.Column("seo_title", sa.String(length=255), nullable=True),
        sa.Column("seo_description", sa.String(length=500), nullable=True),
        sa.Column(
            "created_at",
            app.db.UTCDateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            app.db.UTCDateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint("id = 1", name="ck_site_settings_singleton"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "social_links",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("platform", sa.String(length=60), nullable=False),
        sa.Column("label", sa.String(length=120), nullable=True),
        sa.Column("url", sa.String(length=500), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            app.db.UTCDateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            app.db.UTCDateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("platform"),
    )
    op.create_table(
        "audit_logs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("admin_user_id", sa.Integer(), nullable=True),
        sa.Column("action", sa.String(length=80), nullable=False),
        sa.Column("entity_type", sa.String(length=60), nullable=True),
        sa.Column("entity_id", sa.String(length=64), nullable=True),
        sa.Column("summary", sa.String(length=500), nullable=True),
        sa.Column(
            "created_at",
            app.db.UTCDateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["admin_user_id"], ["admin_users.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("audit_logs", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_audit_logs_action"), ["action"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_audit_logs_admin_user_id"), ["admin_user_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_audit_logs_created_at"), ["created_at"], unique=False
        )

    op.create_table(
        "orders",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("order_number", sa.String(length=32), nullable=False),
        sa.Column("customer_id", sa.Integer(), nullable=True),
        sa.Column("subtotal", app.db.Money(precision=12, scale=2), nullable=False),
        sa.Column("discount_total", app.db.Money(precision=12, scale=2), nullable=False),
        sa.Column("shipping_total", app.db.Money(precision=12, scale=2), nullable=False),
        sa.Column("total", app.db.Money(precision=12, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column(
            "payment_status",
            sa.Enum(
                "PENDING",
                "AUTHORIZED",
                "PAID",
                "FAILED",
                "CANCELLED",
                "REFUNDED",
                name="paymentstatus",
                native_enum=False,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column(
            "order_status",
            sa.Enum(
                "PENDING_PAYMENT",
                "PAYMENT_CONFIRMED",
                "PROCESSING",
                "SHIPPED",
                "DELIVERED",
                "CANCELLED",
                "REFUNDED",
                name="orderstatus",
                native_enum=False,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column("promotion_id", sa.Integer(), nullable=True),
        sa.Column("promotion_code_snapshot", sa.String(length=64), nullable=True),
        sa.Column("shipping_name", sa.String(length=255), nullable=False),
        sa.Column("shipping_email", sa.String(length=255), nullable=False),
        sa.Column("shipping_phone", sa.String(length=40), nullable=True),
        sa.Column("shipping_address", sa.String(length=500), nullable=False),
        sa.Column("shipping_city", sa.String(length=160), nullable=False),
        sa.Column("shipping_country", sa.String(length=120), nullable=False),
        sa.Column("shipping_postal_code", sa.String(length=32), nullable=True),
        sa.Column("customer_note", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            app.db.UTCDateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            app.db.UTCDateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["customer_id"], ["customers.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["promotion_id"], ["promotions.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("orders", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_orders_customer_id"), ["customer_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_orders_order_number"), ["order_number"], unique=True
        )
        batch_op.create_index(
            batch_op.f("ix_orders_order_status"), ["order_status"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_orders_payment_status"), ["payment_status"], unique=False
        )
        batch_op.create_index(
            "ix_orders_status_created", ["order_status", "created_at"], unique=False
        )

    op.create_table(
        "products",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("slug", sa.String(length=255), nullable=False),
        sa.Column("brand_id", sa.Integer(), nullable=True),
        sa.Column("short_description", sa.String(length=500), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("price", app.db.Money(precision=12, scale=2), nullable=True),
        sa.Column("compare_at_price", app.db.Money(precision=12, scale=2), nullable=True),
        sa.Column(
            "estimated_market_price", app.db.Money(precision=12, scale=2), nullable=True
        ),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("sku", sa.String(length=64), nullable=False),
        sa.Column("reference_number", sa.String(length=64), nullable=True),
        sa.Column(
            "condition",
            sa.Enum(
                "NEW",
                "UNWORN",
                "EXCELLENT",
                "VERY_GOOD",
                "GOOD",
                name="productcondition",
                native_enum=False,
                length=40,
            ),
            nullable=True,
        ),
        sa.Column("production_year", sa.Integer(), nullable=True),
        sa.Column("movement", sa.String(length=120), nullable=True),
        sa.Column("case_material", sa.String(length=120), nullable=True),
        sa.Column("case_size", sa.String(length=60), nullable=True),
        sa.Column("dial", sa.String(length=120), nullable=True),
        sa.Column("crystal", sa.String(length=120), nullable=True),
        sa.Column("strap_material", sa.String(length=120), nullable=True),
        sa.Column("water_resistance", sa.String(length=60), nullable=True),
        sa.Column("included_items", sa.String(length=255), nullable=True),
        sa.Column("limited_edition", sa.String(length=160), nullable=True),
        sa.Column("warranty_information", sa.Text(), nullable=True),
        sa.Column("shipping_information", sa.Text(), nullable=True),
        sa.Column("instagram_post_url", sa.String(length=500), nullable=True),
        sa.Column("is_unique", sa.Boolean(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("featured", sa.Boolean(), nullable=False),
        sa.Column("new_arrival", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            app.db.UTCDateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            app.db.UTCDateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "price IS NULL OR price >= 0", name="ck_products_price_non_negative"
        ),
        sa.ForeignKeyConstraint(["brand_id"], ["brands.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("products", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_products_active"), ["active"], unique=False)
        batch_op.create_index(
            "ix_products_active_featured", ["active", "featured"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_products_brand_id"), ["brand_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_products_featured"), ["featured"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_products_new_arrival"), ["new_arrival"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_products_reference_number"), ["reference_number"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_products_sku"), ["sku"], unique=True)
        batch_op.create_index(batch_op.f("ix_products_slug"), ["slug"], unique=True)

    op.create_table(
        "promotion_categories",
        sa.Column("promotion_id", sa.Integer(), nullable=False),
        sa.Column("category_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["category_id"], ["categories.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["promotion_id"], ["promotions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("promotion_id", "category_id"),
    )
    op.create_table(
        "inventory",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("low_stock_threshold", sa.Integer(), nullable=False),
        sa.Column(
            "updated_at",
            app.db.UTCDateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint("quantity >= 0", name="ck_inventory_quantity_non_negative"),
        sa.ForeignKeyConstraint(["product_id"], ["products.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("inventory", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_inventory_product_id"), ["product_id"], unique=True
        )

    op.create_table(
        "inventory_transactions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("change_quantity", sa.Integer(), nullable=False),
        sa.Column("quantity_after", sa.Integer(), nullable=False),
        sa.Column(
            "reason",
            sa.Enum(
                "INITIAL_STOCK",
                "MANUAL_ADJUSTMENT",
                "ORDER_CONFIRMED",
                "ORDER_CANCELLED",
                "RETURN",
                "RESTOCK",
                name="inventoryreason",
                native_enum=False,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column("reference_type", sa.String(length=40), nullable=True),
        sa.Column("reference_id", sa.String(length=64), nullable=True),
        sa.Column("note", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at",
            app.db.UTCDateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["product_id"], ["products.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("inventory_transactions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_inventory_transactions_created_at"),
            ["created_at"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_inventory_transactions_product_id"),
            ["product_id"],
            unique=False,
        )

    op.create_table(
        "order_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("order_id", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=True),
        sa.Column("product_name_snapshot", sa.String(length=255), nullable=False),
        sa.Column("brand_name_snapshot", sa.String(length=160), nullable=True),
        sa.Column("sku_snapshot", sa.String(length=64), nullable=False),
        sa.Column("reference_number_snapshot", sa.String(length=64), nullable=True),
        sa.Column("image_url_snapshot", sa.String(length=500), nullable=True),
        sa.Column("unit_price", app.db.Money(precision=12, scale=2), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("discount_amount", app.db.Money(precision=12, scale=2), nullable=False),
        sa.Column("line_total", app.db.Money(precision=12, scale=2), nullable=False),
        sa.ForeignKeyConstraint(["order_id"], ["orders.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["product_id"], ["products.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("order_items", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_order_items_order_id"), ["order_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_order_items_product_id"), ["product_id"], unique=False
        )

    op.create_table(
        "order_status_history",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("order_id", sa.Integer(), nullable=False),
        sa.Column(
            "from_status",
            sa.Enum(
                "PENDING_PAYMENT",
                "PAYMENT_CONFIRMED",
                "PROCESSING",
                "SHIPPED",
                "DELIVERED",
                "CANCELLED",
                "REFUNDED",
                name="orderstatus",
                native_enum=False,
                length=40,
            ),
            nullable=True,
        ),
        sa.Column(
            "to_status",
            sa.Enum(
                "PENDING_PAYMENT",
                "PAYMENT_CONFIRMED",
                "PROCESSING",
                "SHIPPED",
                "DELIVERED",
                "CANCELLED",
                "REFUNDED",
                name="orderstatus",
                native_enum=False,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column("note", sa.String(length=255), nullable=True),
        sa.Column("changed_by_admin_id", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            app.db.UTCDateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["changed_by_admin_id"], ["admin_users.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["order_id"], ["orders.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("order_status_history", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_order_status_history_order_id"), ["order_id"], unique=False
        )

    op.create_table(
        "payments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("order_id", sa.Integer(), nullable=False),
        sa.Column("provider", sa.String(length=60), nullable=False),
        sa.Column("provider_payment_id", sa.String(length=160), nullable=True),
        sa.Column("provider_event_id", sa.String(length=160), nullable=True),
        sa.Column("amount", app.db.Money(precision=12, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "AUTHORIZED",
                "PAID",
                "FAILED",
                "CANCELLED",
                "REFUNDED",
                name="paymentstatus",
                native_enum=False,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column("failure_reason", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at",
            app.db.UTCDateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            app.db.UTCDateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["order_id"], ["orders.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "provider", "provider_payment_id", name="uq_payments_provider_ref"
        ),
        sa.UniqueConstraint("provider_event_id"),
    )
    with op.batch_alter_table("payments", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_payments_order_id"), ["order_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_payments_provider_payment_id"),
            ["provider_payment_id"],
            unique=False,
        )
        batch_op.create_index(batch_op.f("ix_payments_status"), ["status"], unique=False)

    op.create_table(
        "product_categories",
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("category_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["category_id"], ["categories.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["product_id"], ["products.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("product_id", "category_id"),
    )
    op.create_table(
        "product_images",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("url", sa.String(length=500), nullable=False),
        sa.Column("alt_text", sa.String(length=255), nullable=True),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("is_primary", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            app.db.UTCDateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["product_id"], ["products.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("product_images", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_product_images_product_id"), ["product_id"], unique=False
        )

    op.create_table(
        "promotion_products",
        sa.Column("promotion_id", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["product_id"], ["products.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["promotion_id"], ["promotions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("promotion_id", "product_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("promotion_products")
    with op.batch_alter_table("product_images", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_product_images_product_id"))

    op.drop_table("product_images")
    op.drop_table("product_categories")
    with op.batch_alter_table("payments", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_payments_status"))
        batch_op.drop_index(batch_op.f("ix_payments_provider_payment_id"))
        batch_op.drop_index(batch_op.f("ix_payments_order_id"))

    op.drop_table("payments")
    with op.batch_alter_table("order_status_history", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_order_status_history_order_id"))

    op.drop_table("order_status_history")
    with op.batch_alter_table("order_items", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_order_items_product_id"))
        batch_op.drop_index(batch_op.f("ix_order_items_order_id"))

    op.drop_table("order_items")
    with op.batch_alter_table("inventory_transactions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_inventory_transactions_product_id"))
        batch_op.drop_index(batch_op.f("ix_inventory_transactions_created_at"))

    op.drop_table("inventory_transactions")
    with op.batch_alter_table("inventory", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_inventory_product_id"))

    op.drop_table("inventory")
    op.drop_table("promotion_categories")
    with op.batch_alter_table("products", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_products_slug"))
        batch_op.drop_index(batch_op.f("ix_products_sku"))
        batch_op.drop_index(batch_op.f("ix_products_reference_number"))
        batch_op.drop_index(batch_op.f("ix_products_new_arrival"))
        batch_op.drop_index(batch_op.f("ix_products_featured"))
        batch_op.drop_index(batch_op.f("ix_products_brand_id"))
        batch_op.drop_index("ix_products_active_featured")
        batch_op.drop_index(batch_op.f("ix_products_active"))

    op.drop_table("products")
    with op.batch_alter_table("orders", schema=None) as batch_op:
        batch_op.drop_index("ix_orders_status_created")
        batch_op.drop_index(batch_op.f("ix_orders_payment_status"))
        batch_op.drop_index(batch_op.f("ix_orders_order_status"))
        batch_op.drop_index(batch_op.f("ix_orders_order_number"))
        batch_op.drop_index(batch_op.f("ix_orders_customer_id"))

    op.drop_table("orders")
    with op.batch_alter_table("audit_logs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_audit_logs_created_at"))
        batch_op.drop_index(batch_op.f("ix_audit_logs_admin_user_id"))
        batch_op.drop_index(batch_op.f("ix_audit_logs_action"))

    op.drop_table("audit_logs")
    op.drop_table("social_links")
    op.drop_table("site_settings")
    with op.batch_alter_table("promotions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_promotions_starts_at"))
        batch_op.drop_index(batch_op.f("ix_promotions_ends_at"))
        batch_op.drop_index(batch_op.f("ix_promotions_code"))
        batch_op.drop_index(batch_op.f("ix_promotions_active"))

    op.drop_table("promotions")
    with op.batch_alter_table("posts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_posts_status"))
        batch_op.drop_index(batch_op.f("ix_posts_slug"))
        batch_op.drop_index(batch_op.f("ix_posts_published_at"))
        batch_op.drop_index(batch_op.f("ix_posts_category"))

    op.drop_table("posts")
    op.drop_table("homepage_sections")
    with op.batch_alter_table("customers", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_customers_email"))

    op.drop_table("customers")
    with op.batch_alter_table("categories", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_categories_slug"))
        batch_op.drop_index(batch_op.f("ix_categories_active"))

    op.drop_table("categories")
    with op.batch_alter_table("brands", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_brands_slug"))
        batch_op.drop_index(batch_op.f("ix_brands_active"))

    op.drop_table("brands")
    with op.batch_alter_table("banners", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_banners_active"))

    op.drop_table("banners")
    with op.batch_alter_table("admin_users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_admin_users_email"))

    op.drop_table("admin_users")
    # ### end Alembic commands ###
