"""inquiries

Revision ID: 42492ef288f2
Revises: 338345ca03da
Create Date: 2026-09-22 21:49:25.915427
"""

from collections.abc import Sequence

import sqlalchemy as sa

import app.db  # custom column types (Money, UTCDateTime)
from alembic import op

revision: str = "42492ef288f2"
down_revision: str | None = "338345ca03da"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "inquiries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=True),
        sa.Column("product_name_snapshot", sa.String(length=255), nullable=True),
        sa.Column("full_name", sa.String(length=160), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("phone", sa.String(length=40), nullable=False),
        sa.Column("message", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "NEW",
                "CONTACTED",
                "CLOSED",
                name="inquirystatus",
                native_enum=False,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            app.db.UTCDateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            app.db.UTCDateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["product_id"], ["products.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("inquiries", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_inquiries_product_id"), ["product_id"], unique=False
        )
        batch_op.create_index(
            "ix_inquiries_status_created", ["status", "created_at"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("inquiries", schema=None) as batch_op:
        batch_op.drop_index("ix_inquiries_status_created")
        batch_op.drop_index(batch_op.f("ix_inquiries_product_id"))

    op.drop_table("inquiries")
    # ### end Alembic commands ###
